config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories

  root 'welcome#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :title, :overview, :story
  validates_uniqueness_of :title
  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :subjects, :computer_languages, :project_types
  has_attached_file :attachment
  validates_with AttachmentSizeValidator, attributes: :attachment, less_than: 15.megabytes
  validates_attachment :attachment, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "application/pdf", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.openxmlformats-officedocument.presentationml.presentation"] }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.where('published IS NOT NULL').order('published desc')
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.user = current_user
    if params[:commit] == 'Save and Publish'
      @story.published = Time.now
    end

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    if params[:commit] == 'Save and Publish'
      @story.published ||= Time.now
    end
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :overview, :story, :source, :user_id, :published, :subject_list, :computer_language_list, :project_type_list, :attachment)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      @most_recent_stories = Story.last(3)
      @most_popular_stories = Story.first(3) #TODO calculate actual most popular stories
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "3.3.6"
  end

  def active?(path)
    current_page?(path) ? 'active' : ''
  end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'TechEdSpotlight', root_path, {class: "navbar-brand"} %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class=<%= active?(root_path)%> ><%= link_to 'Home', root_path %></li>
          <li class=<%= active?(stories_path)%> ><%= link_to 'Stories', stories_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to('Submit a Story', new_story_path)  %></li>
          <%= render 'users/menu/login_items.html.erb' %>
          <%= render 'users/menu/registration_items.html.erb' %>
        </ul>
      </div><!--/.nav-collapse -->
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechEdSpotlight</title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="collapsing_header">
  <%= render 'layouts/header.html.erb' %>
  <%= yield :slider %>
  <div class="main">
    <section>
      <container>
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </container>
    </section>
  </div>
  <script src="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>
</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story, html: { multipart: true }) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :overview %><br>
    <%= f.text_field :overview %>
  </div>
  <div class="field">
    <%= f.label :story %><br>
    <%= f.text_area :story %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :subject_list %><br>
    <%= f.text_field :subject_list %>
  </div>
  <div class="field">
    <%= f.label :computer_language_list %><br>
    <%= f.text_field :computer_language_list %>
  </div>
  <div class="field">
    <%= f.label :project_type_list %><br>
    <%= f.text_field :project_type_list %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
    <%= f.submit 'Save and Publish' %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stories</h1>

<%= link_to '[+] New Story', new_story_path %>

<% @stories.in_groups_of(3) do |row_stories| %>
  <div class="row">
    <% row_stories.each do |story| %>
      <div class="col-sm-4">
        <h3><%= link_to story.title, story %></h3>
        <span><em><%= story.published.strftime("%B %d, %Y") %></em></span>
        <p><%= story.overview %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @story.title %></h1>

<p>
  <span><strong>By <%= "#{@story.user.fname} #{@story.user.lname}" %></strong></span>
  <span><%= @story.published.strftime("%B %d, %Y") %></span>
</p>

<p>
  <%= @story.story %>
</p>

<% if @story.source %>
  <p>
    <strong>Source:</strong>
    <%= @story.source %>
  </p>
<% end %>

<p>
  <strong>Attachments:</strong>
  <%= link_to @story.attachment.original_filename, @story.attachment.url %>
</p>

<p>
  <%= link_to 'Edit', edit_story_path(@story) %> |
  <%= link_to 'Delete', @story, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

<p>
  <%= link_to 'Back to Stories', stories_path %>
</p>

app/views/users/menu/_login_items.html.erb
<% if user_signed_in? %>
  <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
  
<% else %>
  <li>
      <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

app/views/users/menu/_registration_items.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to(current_user.email, edit_user_registration_path) %>
  </li>
<% else %>
  <li>
    <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<% content_for :slider do %>
  <section id="slider_wrapper" class="slider_wrapper full_page_photo">
    <div id="main_flexslider" class="flexslider">
      <ul class="slides">
        <li class="item" 
            style="background-image: url(<%= asset_path('banner_placeholder_1.jpg')%>)">
          <div class="container">
           <div class="carousel-caption">
            <h1>A one liner about TechEdSpotlight</h1>
            <p class="lead skincolored">cleanstart is based on good typography and large photography, serving as a foundation for your creative projects. Feel free to browse its templates and discover its features.</p>
            </div>
          </div>
        </li>
        <li class="item"
          style="background-image: url(<%= asset_path('banner_placeholder_2.jpg')%>)">
          <div class="container">
           <div class="carousel-caption">
            <h1>Another one liner</h1>
            <p class="lead skincolored">cleanstart is based on good typography and large photography, serving as a foundation for your creative projects. Feel free to browse its templates and discover its features.</p>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </section>
<% end %>

<row>
  <div class='col-md-4'>
    <h2>Most Recent</h2>
    <ul class='list-group'>
      <% @most_recent_stories.each do |story| %>
      <li class='list-group-item'><%= link_to story.title, story %></li>
      <% end %>
    </ul>
  </div>
  <div class='col-md-4'>
    <h2>Most Popular</h2>
    <ul class='list-group'>
      <% @most_popular_stories.each do |story| %>
      <li class='list-group-item'><%= link_to story.title, story %></li>
      <% end %>
    </ul>
  </div>
  <div class='col-md-4'>
    <h2>Topics</h2>
    <ul class='list-group'>
      <li class='list-group-item'>Fix a CMOS batter problem on a laptop by mr electro in Computers</li>
      <li class='list-group-item'>Fix a CMOS batter problem on a laptop by mr electro in Computers</li>
      <li class='list-group-item'>Fix a CMOS batter problem on a laptop by mr electro in Computers</li>
    </ul>
  </div>
</row>